blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("home/",views.home,name='home'),
    path("subject/",views.subject,name='subject'),
    path("subject/<slug:slug>/",views.subject_deatil,name='subject_deatil'),
    path("article/",views.article,name='article'),
    path("article/<slug:slug>/",views.detail,name='detail'),
    path("article/changelike/",views.changelike,name='changelike'),
    path("tool/",views.tool,name = "tool"),
    path("about/",views.about,name = "about"),
]

oauth/urls.py
from django.urls import path
from . import views

app_name = 'oauth'
urlpatterns = [
    path("login/",views.login,name='login'),
    path("register/",views.register,name='register'),
    path("forget_pwd/",views.forget_pwd,name='forget_pwd'),
    path("logout/",views.logout,name='logout'),
    path("send_verification_code/",views.send_verification_code,name='send_verification_code'),
]

sdfblog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from blog.views import home

urlpatterns = [
    path("admin/",admin.site.urls),
    path(r'mdeditor/', include('mdeditor.urls')),
    path("",home),
    path("oauth/", include("oauth.urls",namespace="oauth")),
    path("blog/", include("blog.urls",namespace="blog")),
    path("comment/", include("comment.urls",namespace="comment")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

oauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Ouser(AbstractUser):
    avatar = ProcessedImageField(upload_to='avatar/%Y%m%d',
                                 default='avatar/default.png',
                                 verbose_name='头像',
                                 processors=[ResizeToFill(80,80)]
                                 )
    nickname = models.CharField(max_length=10,default='访客')
    vip = models.BooleanField(default=False,verbose_name='用户是否是vip')

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return f'User: {self.username}'

oauth/forms.py
from django import forms
from django.contrib import auth

class ForgetPwdForm(forms.Form):
    email = forms.EmailField()
    send_for = forms.CharField()
    vercode = forms.CharField()
    password = forms.CharField()
    confirmPassword = forms.CharField()

    def __init__(self,*args, **kwargs):
        # 初始化表单的时候，需要将request传进来，获取session中验证码
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ForgetPwdForm,self).__init__(*args, **kwargs)

    def clean(self):
        User = auth.get_user_model()

        # 判断邮箱是否存在
        email = self.cleaned_data['email']
        if not User.objects.filter(username = email).exists():
            raise forms.ValidationError('用户邮箱不存在')

        # 判断验证码是否正确
        send_for = self.cleaned_data['send_for']
        vercode_session = self.request.session.get(send_for,'')
        vercode = self.cleaned_data['vercode']
        if vercode_session != vercode:
            raise forms.ValidationError('验证码不正确')

        user = User.objects.get(username = email)
        self.cleaned_data['user'] = user

        return self.cleaned_data

    def clean_confirmPassword(self):
        confirmPassword = self.cleaned_data['confirmPassword']
        password = self.cleaned_data['password']
        if confirmPassword != '' and confirmPassword != password:
            raise ValueError('两次输入的密码不一致')
        return confirmPassword

oauth/views.py
import random
import string
import time

from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.http.response import JsonResponse
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse

from .forms import ForgetPwdForm

User = auth.get_user_model()

# Create your views here.
def login(request):
    context = {
        'nav_item':'login'
    }
    if request.user.is_authenticated:
        return redirect(reverse('blog:home'))
    if request.method == 'GET':
        return render(request,'oauth/login.html',context = context)
    elif request.method == 'POST':
        email = request.POST.get('email')
        pwd = request.POST.get('password')

        # 查询邮箱对应的用户名
        if not User.objects.filter(username = email).exists():
            context['status'] = '0'
            context['error'] = '用户邮箱不存在或密码错误!'
        else:
            user = auth.authenticate(username = email,password = pwd)
            if user is None:
                context['status'] = '0'
                context['error'] = '邮箱不存在或密码错误!'
            else:
                auth.login(request,user)
                context['status'] = '1'
                if request.GET.get('from') == reverse('oauth:register'):
                    context['jump_url'] = reverse('blog:home')
                else:
                    context['jump_url'] = request.GET.get('from', reverse('blog:home'))
        return JsonResponse(context)
    else:
        context['status'] = '0'
        context['error'] = '近接受GET/POST请求!'
        return JsonResponse()

def register(request):
    context = {
        'nav_item': 'register'
    }
    if request.user.is_authenticated:
        return redirect(reverse('blog:home'))
    if request.method == 'GET':
        return render(request,'oauth/register.html',context = context)
    elif request.method == 'POST':
        email = request.POST.get('email')
        send_for = request.POST.get('send_for')
        vercode = request.POST.get('vercode')
        password = request.POST.get('password')
        confirmPassword = request.POST.get('confirmPassword')
        nickname = request.POST.get('nickname')

        # 判断验证码是否一致
        vercode_session = request.session.get(send_for,'')
        if vercode_session != vercode:
            context['status'] = '0'
            context['error'] = '验证码不正确'
            return JsonResponse(context)

        # 判断密码是否一致
        if password != confirmPassword:
            context['status'] = '0'
            context['error'] = '两次输入的密码不一致'
            return JsonResponse(context)

        # 判断邮箱是否重复
        if User.objects.filter(email = email).exists():
            context['status'] = '0'
            context['error'] = '不能重复注册，请换一个邮箱'
            return JsonResponse(context)

        user = User()
        user.username = email
        user.email = email
        user.set_password(password)
        user.nickname = nickname
        user.save()
        context['status'] = '1'
        return JsonResponse(context)
    else:
        context['status'] = '0'
        context['error'] = '近接受GET/POST请求!'
        return JsonResponse(context)

# 用forms做数据验证
def forget_pwd(request):
    context = {
    }
    if request.method == 'GET':
        return render(request,'oauth/forget_pwd.html',context = context)
    elif request.method == 'POST':
        forgetPwdForm = ForgetPwdForm(request.POST,request = request)
        if forgetPwdForm.is_valid():
            data = forgetPwdForm.cleaned_data
            user = data['user']
            pwd = data['confirmPassword']
            user.set_password(pwd)
            user.save()
            context['status'] = '1'
            return JsonResponse(context)
        else:
            context['status'] = '0'
            context['error'] = forgetPwdForm.errors['__all__'][0]  # form错误返回的是字典
            return JsonResponse(context)
    else:
        context['status'] = '0'
        context['error'] = '近接受GET/POST请求!'
        return JsonResponse(context)

@login_required(login_url='oauth:login')
def logout(request):
    jump_url = request.GET.get('from',reverse('blog:home'))
    auth.logout(request)
    return redirect(jump_url)

def send_verification_code(request):
    email = request.GET.get('email','')
    send_for = request.GET.get('send_for','')
    subject = request.GET.get('subject','')
    context = {
    }

    if email != '':
        user_exist = User.objects.filter(email=email).exists()
        if send_for == 'reset_pwd_code' and not user_exist:
            context['status'] = '0'
            context['error'] = '邮箱不存在'
        elif send_for == 'register_code' and user_exist:
            context['status'] = '0'
            context['error'] = '不能重复注册，请换一个邮箱'
        else:
            # 生成验证码
            code = ''.join(random.sample(string.ascii_letters + string.digits, 4))
            now = int(time.time())
            send_code_time = request.session.get('send_code_time', 0)
            if now - send_code_time < 30:
                context['status'] = '0'
                context['error'] = '30s内不能重复发送验证码'
            else:
                request.session[send_for] = code
                request.session['send_code_time'] = now
                context['status'] = '1'
                # 发送邮件
                send_mail(
                    subject = subject,
                    message = f'您的验证码是：{code}',
                    from_email = settings.EMAIL_HOST_USER,
                    recipient_list = [email],
                    fail_silently=False
                )
    else:
        context['status'] = '0'
        context['error'] = '邮箱不能为空'

    return JsonResponse(context)

templates/oauth/forget_pwd.html
{% extends 'base.html' %}
{% load static %}

{% block title %}找回密码{% endblock %}

{% block main_content %}
<div class="layui-container ws-container">
    <div class="reg-container">
        <h2 class="title">找&nbsp;回&nbsp;密&nbsp;码</h2>
        <form class="layui-form">
            <div class="layui-form-item">
                <div class="layui-row">
                    <div class="layui-col-xs8">
                        <div class="layui-input-wrap">
                            <div class="layui-input-prefix">
                                <i class="layui-icon layui-icon-email"></i>
                            </div>
                            <input type="text" name="email" value="" lay-verify="required|email" placeholder="邮箱" lay-reqtext="请填写邮箱" autocomplete="off" class="layui-input" id="reg-email">
                        </div>
                    </div>
                    <div class="layui-col-xs4">
                        <div style="margin-left: 11px;">
                            <button type="button" class="layui-btn layui-btn-fluid layui-btn-primary" lay-on="reg-get-vercode">获取验证码</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-wrap">
                    <div class="layui-input-prefix">
                        <i class="layui-icon layui-icon-vercode"></i>
                    </div>
                    <input type="text" name="vercode" value="" lay-verify="required" placeholder="验证码" lay-reqtext="请填写验证码" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-wrap">
                    <div class="layui-input-prefix">
                        <i class="layui-icon layui-icon-password"></i>
                    </div>
                    <input type="password" name="password" value="" lay-verify="required" placeholder="密码"
                           autocomplete="off" class="layui-input" id="reg-password" lay-affix="eye">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-wrap">
                    <div class="layui-input-prefix">
                        <i class="layui-icon layui-icon-password"></i>
                    </div>
                    <input type="password" name="confirmPassword" value="" lay-verify="required|confirmPassword" placeholder="确认密码" autocomplete="off" class="layui-input" lay-affix="eye">
                </div>
            </div>
            <div class="layui-form-item">
                <button class="layui-btn layui-btn-fluid" lay-submit lay-filter="find">找回密码</button>
            </div>
            <div class="layui-form-item reg-other">
                或 <a href="{% url 'oauth:login' %}">登录已有帐号</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block extended_js %}
    <script>
        layui.use(function () {
            var $ = layui.$;
            var form = layui.form;
            var layer = layui.layer;
            var util = layui.util;
            let send_for = 'reset_pwd_code';

            // 自定义验证规则
            form.verify({
                // 确认密码
                confirmPassword: function (value, item) {
                    var passwordValue = $('#reg-password').val();
                    if (value !== passwordValue) {
                        return '两次密码输入不一致';
                    }
                }
            });

            // 提交事件
            form.on('submit(find)', function (data) {
                var field = data.field; // 获取表单字段值
                field['send_for'] = send_for;
                // layer.msg(field, {icon: 5});
                // 此处可执行 Ajax 等操作
                $.ajax({
                    type: 'post',
                    url: '{% url 'oauth:forget_pwd' %}',
                    headers: {'x-CSRFToken':'{{ csrf_token }}'},
                    dataType: 'json',
                    data: field,
                    success: function (data) {
                        if(data.status == '1'){
                            location.href = '{% url "oauth:login" %}'
                        }else{
                            layer.msg(data.error, {icon: 5});
                        }
                    },
                    error: function (data) {
                        console.log(data);
                    }
                });

                return false; // 阻止默认 form 跳转
            });

            // 普通事件
            util.on('lay-on', {
                // 获取验证码
                'reg-get-vercode': function (othis) {
                    var isvalid = form.validate('#reg-email'); // 主动触发验证，v2.7.0 新增
                    // 验证通过
                    if (isvalid) {
                        // 把按钮置为灰色
                        $(this).addClass('disabled');
                        $(this).attr('disabled', true);
                        var time = 30;
                        $(this).text(time + 's');
                        var interval = setInterval(() => {
                            if(time <= 0){
                                clearInterval(interval);
                                $(this).removeClass('disabled');
                                $(this).attr('disabled', false);
                                $(this).text('发送验证码');
                                return false;
                            }

                            time --;
                            $(this).text(time + 's');
                        }, 1000);
                        // 此处可继续书写「发送验证码」等后续逻辑
                        $.ajax({
                           type: "GET",
                            url: "{% url 'oauth:send_verification_code' %}",
                            data: {
                               'email': $('#reg-email').val(),
                                'send_for': send_for,
                                'subject': '重置密码'
                            },
                            cache: false,
                            success: function (data) {
                                if(data.status == '0'){
                                    layer.msg(data.error, {icon: 5});
                                }else{
                                    layer.msg('发送验证码成功！', {icon: 1});
                                }
                            }
                        });
                    }
                }
            });
        });
    </script>
{% endblock %}

templates/oauth/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}登录{% endblock %}

{% block main_content %}
<div class="layui-container ws-container">
    <div class="login-container">
        <h2 class="title">登&nbsp;&nbsp;&nbsp;录</h2>
        <form class="layui-form">
            {% csrf_token %}
            <div class="layui-form-item">
                <div class="layui-input-wrap">
                    <div class="layui-input-prefix">
                        <i class="layui-icon layui-icon-email"></i>
                    </div>
                    <input type="text" name="email" value="" lay-verify="required|email" placeholder="邮箱" lay-reqtext="请填写邮箱" autocomplete="off" class="layui-input" id="reg-email">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-wrap">
                    <div class="layui-input-prefix">
                        <i class="layui-icon layui-icon-password"></i>
                    </div>
                    <input type="password" name="password" value="" lay-verify="required" placeholder="密   码" lay-reqtext="请填写密码" autocomplete="off" class="layui-input" lay-affix="eye">
                </div>
            </div>
            <div class="layui-form-item">
                <input type="checkbox" name="remember" lay-skin="primary" title="记住密码">
                <a href="{% url 'oauth:forget_pwd' %}" style="float: right; margin-top: 7px;">忘记密码？</a>
            </div>
            <div class="layui-form-item">
                <button class="layui-btn layui-btn-fluid" lay-submit lay-filter="login">登录</button>
            </div>
            <div class="layui-form-item login-other">
                或 <a href="{% url 'oauth:register' %}" >注册帐号</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block extended_js %}
    <script>
        layui.use(function () {
            var form = layui.form;
            var layer = layui.layer;
            // 提交事件
            form.on('submit(login)', function (data) {
                var field = data.field; // 获取表单字段值
                // 提交请求
                $.ajax({
                    type: 'post',
                    url: location.href,
                    headers: {'x-CSRFToken':'{{ csrf_token }}'},
                    dataType: 'json',
                    data: field,
                    success: function (data) {
                        if(data.status == '1'){
                            location.href = data.jump_url
                        }else{
                            layer.msg(data.error, {icon: 4});
                        }
                    },
                    error: function (data) {
                        console.log(data);
                    }
                });
                return false; // 阻止默认 form 跳转
            });
        });
    </script>
{% endblock %}

templates/oauth/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}注册{% endblock %}

{% block main_content %}
<div class="layui-container ws-container">
    <div class="reg-container">
        <h2 class="title">注&nbsp;&nbsp;&nbsp;册</h2>
        <form class="layui-form">
            {% csrf_token %}
            <div class="layui-form-item">
                <div class="layui-row">
                    <div class="layui-col-xs8">
                        <div class="layui-input-wrap">
                            <div class="layui-input-prefix">
                                <i class="layui-icon layui-icon-email"></i>
                            </div>
                            <input type="text" name="email" value="" lay-verify="required|email" placeholder="邮箱" lay-reqtext="请填写邮箱" autocomplete="off" class="layui-input" id="reg-email">
                        </div>
                    </div>
                    <div class="layui-col-xs4">
                        <div style="margin-left: 11px;">
                            <button type="button" class="layui-btn layui-btn-fluid layui-btn-primary" lay-on="reg-get-vercode">获取验证码</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-wrap">
                    <div class="layui-input-prefix">
                        <i class="layui-icon layui-icon-vercode"></i>
                    </div>
                    <input type="text" name="vercode" value="" lay-verify="required" placeholder="验证码" lay-reqtext="请填写验证码" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-wrap">
                    <div class="layui-input-prefix">
                        <i class="layui-icon layui-icon-password"></i>
                    </div>
                    <input type="password" name="password" value="" lay-verify="required" placeholder="密码" autocomplete="off" class="layui-input" id="reg-password" lay-affix="eye">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-wrap">
                    <div class="layui-input-prefix">
                        <i class="layui-icon layui-icon-password"></i>
                    </div>
                    <input type="password" name="confirmPassword" value="" lay-verify="required|confirmPassword" placeholder="确认密码" autocomplete="off" class="layui-input" lay-affix="eye">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-wrap">
                    <div class="layui-input-prefix">
                        <i class="layui-icon layui-icon-username"></i>
                    </div>
                    <input type="text" name="nickname" value="" lay-verify="required|nickname" placeholder="昵称(10字以内)" autocomplete="off" class="layui-input" lay-affix="clear">
                </div>
            </div>
            <div class="layui-form-item">
                <button class="layui-btn layui-btn-fluid" lay-submit lay-filter="reg">注册</button>
            </div>
            <div class="layui-form-item reg-other">
                <a href="{% url 'oauth:login' %}">登录已有帐号</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block extended_js %}
    <script>
        layui.use(function () {
            var $ = layui.$;
            var form = layui.form;
            var layer = layui.layer;
            var util = layui.util;
            let send_for = 'register_code';

            // 自定义验证规则
            form.verify({
                // 确认密码
                confirmPassword: function (value, item) {
                    var passwordValue = $('#reg-password').val();
                    if (value !== passwordValue) {
                        return '两次密码输入不一致';
                    }
                },
                // 确认密码
                nickname: function (value, item) {
                    if (value.length > 10) {
                        return '昵称太长，请输入10个字符以内的字符';
                    }
                }
            });

            // 提交事件
            form.on('submit(reg)', function (data) {
                var field = data.field; // 获取表单字段值
                field['send_for'] = send_for;

                // 此处可执行 Ajax 等操作
                $.ajax({
                    type: 'post',
                    url: '{% url 'oauth:register' %}',
                    headers: {'x-CSRFToken':'{{ csrf_token }}'},
                    dataType: 'json',
                    data: field,
                    success: function (data) {
                        if(data.status == '1'){
                            location.href = '{% url "oauth:login" %}'
                        }else{
                            layer.msg(data.error, {icon: 5});
                        }
                    },
                    error: function (data) {
                        console.log(data);
                    }
                });

                return false; // 阻止默认 form 跳转
            });

            // 普通事件
            util.on('lay-on', {
                // 获取验证码
                'reg-get-vercode': function (othis) {
                    var isvalid = form.validate('#reg-email'); // 主动触发验证，v2.7.0 新增
                    // 验证通过
                    if (isvalid) {
                        // 把按钮置为灰色
                        $(this).addClass('disabled');
                        $(this).attr('disabled', true);
                        var time = 30;
                        $(this).text(time + 's');
                        var interval = setInterval(() => {
                            if(time <= 0){
                                clearInterval(interval);
                                $(this).removeClass('disabled');
                                $(this).attr('disabled', false);
                                $(this).text('发送验证码');
                                return false;
                            }

                            time --;
                            $(this).text(time + 's');
                        }, 1000);
                        // 此处可继续书写「发送验证码」等后续逻辑
                        $.ajax({
                           type: "GET",
                            url: "{% url 'oauth:send_verification_code' %}",
                            data: {
                               'email': $('#reg-email').val(),
                                'send_for': send_for,
                                'subject': '注册用户'
                            },
                            cache: false,
                            success: function (data) {
                                if(data.status == '0'){
                                    layer.msg(data.error, {icon: 5});
                                }else{
                                    layer.msg('发送验证码成功！', {icon: 1});
                                }
                            }
                        });
                    }
                }
            });
        });
    </script>
{% endblock %}