blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("home/",views.home,name='home'),
    path("subject/",views.subject,name='subject'),
    path("subject/<slug:slug>/",views.subject_deatil,name='subject_deatil'),
    path("article/",views.article,name='article'),
    path("article/<slug:slug>/",views.detail,name='detail'),
    path("article/changelike/",views.changelike,name='changelike'),
    path("tool/",views.tool,name = "tool"),
    path("about/",views.about,name = "about"),
]

oauth/urls.py
from django.urls import path
from . import views

app_name = 'oauth'
urlpatterns = [
    path("login/",views.login,name='login'),
    path("register/",views.register,name='register'),
    path("forget_pwd/",views.forget_pwd,name='forget_pwd'),
    path("logout/",views.logout,name='logout'),
    path("send_verification_code/",views.send_verification_code,name='send_verification_code'),
]

sdfblog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from blog.views import home

urlpatterns = [
    path("admin/",admin.site.urls),
    path(r'mdeditor/', include('mdeditor.urls')),
    path("",home),
    path("oauth/", include("oauth.urls",namespace="oauth")),
    path("blog/", include("blog.urls",namespace="blog")),
    path("comment/", include("comment.urls",namespace="comment")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}首页{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <link rel="stylesheet" href="https://cdn.staticfile.net/highlight.js/11.4.0/styles/monokai-sublime.min.css">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <script src="https://cdn.staticfile.net/jquery/3.5.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdn.staticfile.net/layui/2.9.0/layui.js" type="text/javascript"></script>
    <script src="https://cdn.staticfile.net/highlight.js/11.4.0/highlight.min.js" type="text/javascript"></script>
    <!-- 本地
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <link rel="stylesheet" href="{% static 'highlight/monokai-sublime.min.css' %}">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <script src="{% static 'jquery-3.5.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'layui/layui.js' %}" type="text/javascript"></script>
    <script src="{% static 'highlight/highlight.min.js' %}" type="text/javascript"></script>
    -->
</head>

<body>
    <!-- 头部导航栏 -->
    <div class="layui-header ws-header ws-bg-light">
        <div class="layui-container">
            <div class="ws-logo">
                <a class="logo" href="{% url 'blog:home' %}"><img src="{% static 'images/logo.png' %}" alt="数据民工"></a>
            </div>
            <div class="ws-header-menu">
                <ul class="layui-nav layui-bg-gray ws-bg-light" id="LAY_NAV_TOP">
                    {% if nav_item == 'home' %}
                        <li class="layui-nav-item layui-this"><a href="{% url 'blog:home' %}">首页</a></li>
                    {% else %}
                        <li class="layui-nav-item"><a href="{% url 'blog:home' %}">首页</a></li>
                    {% endif %}
                    {% if nav_item == 'article' %}
                        <li class="layui-nav-item layui-this"><a href="{% url 'blog:article' %}">文章</a></li>
                    {% else %}
                        <li class="layui-nav-item"><a href="{% url 'blog:article' %}">文章</a></li>
                    {% endif %}
                    {% if nav_item == 'subject' %}
                        <li class="layui-nav-item layui-this"><a href="{% url 'blog:subject' %}">专题</a></li>
                    {% else %}
                        <li class="layui-nav-item"><a href="{% url 'blog:subject' %}">专题</a></li>
                    {% endif %}
                    {% if nav_item == 'tool' %}
                        <li class="layui-nav-item layui-this"><a href="{% url 'blog:tool' %}">工具</a></li>
                    {% else %}
                        <li class="layui-nav-item"><a href="{% url 'blog:tool' %}">工具</a></li>
                    {% endif %}
                    {% if nav_item == 'about' %}
                        <li class="layui-nav-item layui-this"><a href="{% url 'blog:about' %}">关于</a></li>
                    {% else %}
                        <li class="layui-nav-item"><a href="{% url 'blog:about' %}">关于</a></li>
                    {% endif %}
                    {% if not request.user.is_authenticated %}
                        {% if nav_item == 'login' %}
                            <li class="layui-nav-item layui-this"><a href="{% url 'oauth:login' %}?from={{ request.get_full_path }}">登录</a></li>
                        {% else %}
                            <li class="layui-nav-item"><a href="{% url 'oauth:login' %}?from={{ request.get_full_path }}">登录</a></li>
                        {% endif %}
                        {% if nav_item == 'register' %}
                            <li class="layui-nav-item layui-this"><a href="{% url 'oauth:register' %}">注册</a></li>
                        {% else %}
                            <li class="layui-nav-item"><a href="{% url 'oauth:register' %}">注册</a></li>
                        {% endif %}
                    {% else %}
                        {% with request.user as user %}{% endwith %}
                        <li class="layui-nav-item">
                            <a href="javascript:;"><img src="{{ user.avatar.url }}" class="layui-nav-img"></a>
                            <dl class="layui-nav-child layui-nav-child-r">
                                <dd><a href="#">我的主页</a></dd>
                                {% if user.is_staff %}
                                    <dd><a href="/admin" target="_blank">后台管理</a></dd>
                                {% endif %}
                                <hr>
                                <dd><a href="{% url 'oauth:logout' %}?from={{ request.get_full_path }}">退出登录</a></dd>
                            </dl>
                        </li>
                    {% endif %}
                </ul>
                <div class="ws-header-more">
                    <i class="layui-icon layui-icon-shrink-right"></i>
                </div>
            </div>
        </div>
    </div>
    <!-- 内容区 -->
    {% block main_content %}{% endblock %}
    <!-- 页脚 -->
    <div class="layui-footer ws-footer ws-footer-fixed ws-bg-light">
        <div>Copyright © 2023-2023. Powered by Django & Layui.</div>
        <div class="concat_me">
            <span>联系我:</span>
            <i class="layui-icon layui-icon-login-wechat"></i>
            <span>superdatafarmerup</span>
        </div>
    </div>
    <!-- 菜单toggle弹窗遮罩 -->
    <div class="ws-shade"></div>
    <!-- 左下角回到顶部和toc展开图标 -->
    <ul class="layui-fixbar">
        {% block toc_icon %}{% endblock %}
        <li class="layui-icon layui-icon-top layui-fixbar-top" id="top-icon"></li>
    </ul>
    <script src="{% static 'index.js' %}"></script>
    {% block extended_js %}{% endblock %}
    {% block extended_css %}{% endblock %}
</body>
</html>